"""updated user model

Revision ID: 164c1fd415f6
Revises: ee6c4a34264f
Create Date: 2025-06-18 14:14:07.541728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164c1fd415f6'
down_revision = 'ee6c4a34264f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
