"""Remove global unique constraints on subject name/code

Revision ID: 8df82ba3ede7
Revises: f8a4342016f5
Create Date: 2025-06-24 09:59:00.302993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df82ba3ede7'
down_revision = 'f8a4342016f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('subjects_code_key', type_='unique')
        batch_op.drop_constraint('subjects_name_key', type_='unique')
        batch_op.create_unique_constraint('uq_subject_code_per_school', ['school_id', 'code'])
        batch_op.create_unique_constraint('uq_subject_name_per_school', ['school_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subject_name_per_school', type_='unique')
        batch_op.drop_constraint('uq_subject_code_per_school', type_='unique')
        batch_op.create_unique_constraint('subjects_name_key', ['name'])
        batch_op.create_unique_constraint('subjects_code_key', ['code'])

    # ### end Alembic commands ###
