"""Fix competition-quizquestion relationship

Revision ID: ba824089042d
Revises: f4f634b575f0
Create Date: 2025-06-26 12:11:41.372839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba824089042d'
down_revision = 'f4f634b575f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competition_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quiz_submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('quiz_answers', sa.Text(), nullable=True))
        batch_op.alter_column('submission_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint('unique_school_competition', type_='unique')
        batch_op.drop_column('score')
        batch_op.drop_column('joined_at')

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_quiz', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proctoring_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('screen_sharing_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_individual_rankings', sa.Boolean(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('show_individual_rankings')
        batch_op.drop_column('screen_sharing_required')
        batch_op.drop_column('proctoring_enabled')
        batch_op.drop_column('time_limit')
        batch_op.drop_column('has_quiz')

    with op.batch_alter_table('competition_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('unique_school_competition', ['competition_id', 'school_id'])
        batch_op.alter_column('submission_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('quiz_answers')
        batch_op.drop_column('quiz_submitted_at')
        batch_op.drop_column('quiz_score')

    op.drop_table('quiz_questions')
    # ### end Alembic commands ###
