"""removed subcounty and ward

Revision ID: 52ec0ea51df7
Revises: 8778ff789db6
Create Date: 2025-06-11 19:31:44.466183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ec0ea51df7'
down_revision = '8778ff789db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('sub_county')
        batch_op.drop_column('ward')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ward', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sub_county', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
