"""Add dashboard customization fields to School model

Revision ID: db9cfa359c05
Revises: 72ed070e756a
Create Date: 2025-06-14 09:26:19.934548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9cfa359c05'
down_revision = '72ed070e756a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('primary_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('secondary_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('enabled_modules', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('dashboard_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_column('dashboard_config')
        batch_op.drop_column('enabled_modules')
        batch_op.drop_column('secondary_color')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
