"""Add subject to Competition

Revision ID: f0b7dd1df70c
Revises: 8dfb9d5484d3
Create Date: 2025-06-26 13:07:53.787714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b7dd1df70c'
down_revision = '8dfb9d5484d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
