"""Add dashboard settings fields

Revision ID: f3c54e5d528d
Revises: 0479cdb60b90
Create Date: 2025-06-23 11:11:31.323858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c54e5d528d'
down_revision = '0479cdb60b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branding_background', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('branding_font_color', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_background', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dashboard_font_color', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dashboard_font_color')
        batch_op.drop_column('dashboard_background')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('branding_font_color')
        batch_op.drop_column('branding_background')

    # ### end Alembic commands ###
